---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookshelf-ebook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: store-k8s
  target:
    name: bookshelf-ebook-secret
    template:
      engineVersion: v2
      data:
        READARR__AUTH__APIKEY: "{{ .bookshelf_ebook_api_key }}"

        READARR__POSTGRES__HOST: &dbHost "{{ .PG_HOST }}"
        READARR__POSTGRES__USER: &dbUser "{{ .bookshelf_ebook_postgres_user }}"
        READARR__POSTGRES__PASSWORD: &dbPass "{{ .bookshelf_ebook_postgres_pass }}"
        READARR__POSTGRES__MAINDB: "{{ .bookshelf_ebook_postgres_maindb }}"
        READARR__POSTGRES__CACHEDB: "{{ .bookshelf_ebook_postgres_cachedb }}"
        READARR__POSTGRES__LOGDB: "{{ .bookshelf_ebook_postgres_logdb }}"

        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_root_pass }}"
        INIT_POSTGRES_SUPER_USER: "{{ .postgres_root_user }}"
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_DBNAME: >-
          {{ .bookshelf_ebook_postgres_maindb }}
          {{ .bookshelf_ebook_postgres_cachedb }}
          {{ .bookshelf_ebook_postgres_logdb }}
  dataFrom:
    - extract:
        key: everything
    - extract:
        key: service-hosts
